spring:
  application:
    name: droneia
  webflux:
    base-path: /elmenus
  r2dbc:
    url: r2dbc:${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

aws: # remove keys for GitHub push
  access-key:
  secret-key:
  s3:
    bucket: droneia
    region: us-east-1
    endpoint: http://localhost:8080


jwt:
  signing:
    key: i-am-signing-key

drone:
  battery-drain-rate: 10000